name: Lint Code with clang-tidy and clang-format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Clang
      - name: Install Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y clang clang-tidy clang-format

      # Run clang-format to check if the code is formatted
      - name: Check code format with clang-format
        run: |
          # Run clang-format on all .cpp, .h, and other source files excluding thirdparty folder
          find . -path ./thirdparty -prune -o -name '*.{c,cpp,h}' -exec clang-format -i -style=.clang-format {} \; | tee clang-format-output.txt
          # Check if there are any issues in clang-format output
          if [ -s clang-format-output.txt ]; then
            echo "clang-format issues found:"
            cat clang-format-output.txt
            exit 1
          fi

      # Run clang-tidy to check for code quality issues
      - name: Run clang-tidy
        run: |
          # Run clang-tidy on all .cpp, .h, and other source files excluding thirdparty folder
          find . -path ./thirdparty -prune -o -name '*.{c,cpp,h}' | xargs clang-tidy -config='' -checks='*' --quiet | tee clang-tidy-output.txt
          # Check if there are any issues in clang-tidy output
          if [ -s clang-tidy-output.txt ]; then
            echo "clang-tidy issues found:"
            cat clang-tidy-output.txt
            exit 1
          fi
