.TH ATTACKIT 1 "June 2025" "AttacKit 1.0" "User Commands"

.SH NAME
attackit \- Network spoofing and interception tool

.SH SYNOPSIS
.B attackit
[\fIOPTIONS\fR] \fICOMMAND\fR [\fICOMMAND OPTIONS\fR]

.SH DESCRIPTION
AttacKit is a CLI tool for performing network attacks such as ARP spoofing, DNS spoofing, and SSL stripping (via ARP or DNS). It is designed for penetration testers and security researchers to simulate and analyze network vulnerabilities.

The tool supports two primary modes:

.TP
.B Quiet Mode (\fB--quiet\fR)
Targets specific victims and domains/IPs for stealthy, minimal-noise attacks. Requires victim IPs and/or domains depending on the attack. Cannot be used with \fB--all-out\fR.

.TP
.B All-Out Mode (\fB--all-out\fR)
Broadcast mode that targets all devices or DNS queries on the network, useful for rapid and broad attacks. Cannot be used with \fB--quiet\fR.

.SH OPTIONS

.TP
.B --help
Display the help menu.

.TP
.B --quiet
Enable quiet mode: silent targeting of specific IPs/domains. Cannot be combined with --all-out.

.TP
.B --all-out
Enable all-out mode: broad broadcast attacks affecting all targets. Cannot be combined with --quiet.

.SH COMMANDS

.TP
.B --arp
\fIifaceIpOrName\fR [\fIattackerMac\fR] [\fIvictimIp\fR] [\fIipToSpoof\fR]

Perform an ARP spoofing attack. The \fIattackerMac\fR parameter is optional. In quiet mode, \fIvictimIp\fR and \fIipToSpoof\fR are required. Multiple IP addresses can be specified using comma separation.

.TP
.B --dns
\fIifaceIpOrName\fR \fIattackerIp\fR [\fIvictimIps\fR] [\fIdomainsToSpoof\fR]

Perform a DNS spoofing attack. In all-out mode, all DNS queries on the interface are spoofed. In quiet mode, \fIvictimIps\fR and \fIdomainsToSpoof\fR must be specified. Multiple victims and domains can be comma-separated.

.TP
.B --ssldns
\fIifaceIpOrName\fR \fIattackerIp\fR \fIvictimIps\fR \fIdomainsToStrip\fR

Perform a DNS-based SSL stripping attack. In quiet mode, \fIvictimIps\fR and \fIdomainsToStrip\fR must be specified. Multiple victims and domains can be comma-separated.

.TP
.B --sslarp
\fIifaceIpOrName\fR \fIvictimIps\fR \fIdomainsToStrip\fR

Perform an ARP-based SSL stripping attack. In quiet mode, \fIvictimIps\fR and \fIdomainsToStrip\fR must be specified. Multiple victims and domains can be comma-separated.

.SH EXAMPLES

.TP
Run an all-out ARP spoofing attack on interface eth0:
.B attackit --arp eth0 --all-out

.TP
Run a quiet DNS spoofing attack on eth0 targeting specific IPs and domains:
.B attackit --quiet --dns eth0 192.168.1.10 192.168.1.15 example.com,google.com

.SH EXIT STATUS
Returns 0 on success, 1 on error.

.SH AUTHOR
Written by the AttacKit development team.

.SH REPORTING BUGS
Report bugs at https://github.com/Schnitzels-tue/AttacKit/issues

.SH COPYRIGHT
Copyright (C) 2025 AttacKit. Licensed under the MIT License.
